// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenMod.WebServer;

namespace OpenMod.WebServer.Migrations
{
    [DbContext(typeof(WebServerDbContext))]
    [Migration("20210221014057_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OpenMod.WebServer.Authentication.AuthToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokeTime")
                        .HasColumnType("datetime");

                    b.HasKey("Token");

                    b.ToTable("OpenMod_WebServer_AuthTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
