database:
  ConnectionStrings:
    default: "Server=127.0.0.1; Database=openmod; Port=3306; User=root"

bind: http://+:27018

# Enables SPA (Single-Page Application) support which is needed for e.g. OpenMod.Dashboard
spaSupport: true