name: NuGet Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version (SemVer: https://semver.org)'
        required: true
jobs:
  deploy:
    name: "OpenMod WebServer and Dashboard NuGet Deployment"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore .
    - name: Update version (WebServer)
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ github.event.inputs.version }}</Version>#\" OpenMod.WebServer/OpenMod.WebServer.csproj" 
    - name: Update version (Dashboard)
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ github.event.inputs.version }}</Version>#\" OpenMod.Dashboard/OpenMod.Dashboard.csproj"       
    - name: Build
      run: dotnet build . --configuration Release --no-restore
    - name: Push to NuGet (WebServer)
      run: dotnet nuget push OpenMod.WebServer/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json
    - name: Push to NuGet (Dashboard)
      run: dotnet nuget push OpenMod.Dashboard/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json             
